### ISSUE TITLE
Skipped values of RangeWidget

### ISSUE THREAD

**Issue by akhmerov** [jakevdp/ipywidgets#15]
Sometimes the `RangeWidget` doesn't correctly update the displayed output. I was able to reproduce the behavior with minimal code:

```python
import ipywidgets
ipywidgets.StaticInteract((lambda x: x), x=ipywidgets.RangeWidget(2, 4, 0.2))
```

Bug description: with the widget above there is no output shown when the slider is set to `x=3` or `x=4`.

This should be something very basic. I know the project is not active for a while, but some pointers to the origin of the error would be greatly appreciated.

**Comment by akhmerov** [comment]
Here's a demonstration: http://nbviewer.ipython.org/urls/dl.dropboxusercontent.com/u/763585/ipywidgets_bug.ipynb

The bug is present in the current master branch.

**Comment by jakevdp** [comment]
This is likely due to floating point representations in Javascript. The best fix is to refactor the code so that the range values are integers.

**Comment by akhmerov** [comment]
Do you mind reopening this? It's still a bug even though the origin may be known.

**Comment by jakevdp** [comment]
I use IPython's built-in HTML widgets. They require a Python kernel so they don't yet allow static output (i.e. nbviewer or HTML-rendered web pages), but that feature is on the roadmap.
