### ISSUE TITLE
Add to ipywidgets PyPI

### ISSUE THREAD

**Issue by jackiekazil** [jakevdp/ipywidgets#17]

**Comment by jakevdp** [comment]
Adding this to PyPI comes with an expectation of support; as I'm no longer supporting this package I think it's not a good idea.

You should use the built-in IPython widgets which came with the 2.x release. There's no static version yet, but that is on the horizon.

**Comment by jackiekazil** [comment]
Maybe update the readme for this repo to direct people to that?  (I had no idea when I visited the repo that was the case.)
