### ISSUE TITLE
StaticInteract error

### ISSUE THREAD

**Issue by fayazr** [jakevdp/ipywidgets#18]
I am getting the following error:

ImportError                               Traceback (most recent call last)
<ipython-input-2-e66f5ca20468> in <module>()
----> 1 from ipywidgets import StaticInteract, RangeWidget, RadioWidget
      2 
      3 StaticInteract(plot,
      4                amplitude=RangeWidget(0.1, 1.0, 0.1),
      5                color=RadioWidget(['blue', 'green', 'red']))

ImportError: cannot import name StaticInteract

**Comment by jakevdp** [comment]
My guess is you're using an older version of the package.

In any case, I'm not supporting this package anymore, and I'd suggest you use IPython's built-in widget tools.
